### ISSUE TITLE
Missing upgrade step

### ISSUE THREAD

**Issue by keul** [RedTurtle/redturtle.tiles.management#3]
I upgraded a Plone 5.1 site where I tested version 0.2.1 to latest master.
It seems that bundle registration is changed but there's no upgrade step right now.

If you try to rerun installation, this lead to two resources (`tiles-management-bundle` and `tiles-management`) in the bundle. This lead to [requires.js error](http://requirejs.org/docs/errors.html#mismatch).

Issues was fixed by manually cleaning the resource registry

**Comment by cekk** [comment]
yes, i've made a huge refactor of this product last week: now it's a pattern that can be included in every page. There is still a 0.x branch with old implementation.

I haven't thinked yet about how to do a proper migration-step (basically because we used it only in one project) because i also need to update the tiles mapping informations

**Comment by cekk** [comment]
@keul added with [this commit](https://github.com/RedTurtle/redturtle.tiles.management/commit/3ad5e67c62e1002f571ddc32fc734019e1ce4aad)
